FROM ubuntu

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    python3-pip \
    python3-setuptools \
    python3-dev \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update

RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install python3-opencv

RUN pip3 install paho-mqtt

RUN mkdir /tmp/ft
WORKDIR /tmp/ft
COPY docker/haarcascade_frontalface_default.xml .
COPY face_detector.py .
CMD ["python3", "face_detector.py"]
